---
title: "Data Exploration"
output: pdf_document
date: "2025-10-16"
---

```{r}
#| label: load-packages-and-data
#| message: false 
library(tidyverse)
library(tidymodels)
library(moments)

training_raw <- read_csv("data-train.csv") #read raw csv



```


```{r}
#| label: calculating-moments-formatting-data

only_raw <- training_raw |>
  mutate(R_moment_0 = 0) |>
  select(R_moment_0, R_moment_1,
         R_moment_2, R_moment_3,
         R_moment_4)

only_raw_t <- as.data.frame(t(only_raw))

training <- as.data.frame(t(raw2central(only_raw_t))) 
training <- training |>
  add_column(St = training_raw$St,
             Re = training_raw$Re,
             Fr = training_raw$Fr,
             .before = 1)
```

```{r}
#| label: EDA-for-models-means

ggplot(training, aes(x = St)) +
  geom_histogram(bins = 10) +
  labs(title = "Histogram of St", x = "Value")

ggplot(training, aes(x = V2)) +
  geom_histogram(bins = 15) +
  labs(title = "Histogram of Means", x = "Value")

ggplot(training, aes(x = St, y = V2, color = factor(Re), shape = factor(Fr))) +
  geom_point()

training |> count(Re, Fr)

training_transformations <- training |>
  mutate(logSt = log(St))

training_transformations <- training_transformations |>
  mutate(log_mean = log(V2))

ggplot(training_transformations, aes(x = logSt)) +
  geom_histogram(binwidth = 0.4) +
  labs(title = "Dot Plot of Log St", x = "Value")

skewness(training$St)
skewness(training_transformations$logSt)
skewness(training$V2)
skewness(training_transformations$log_mean)

ggplot(training_transformations, aes(x = logSt, y = log_mean, color = factor(Re), shape = factor(Fr))) +
  geom_point()
```

